
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using EPiServer.Personalization.VisitorGroups;

namespace PulsePersonalizationApp.SelectionFactories
{
    public class PulseEthnographicSegmentSelectionFactory : ISelectionFactory
    {
        public IEnumerable<SelectListItem> GetSelectListItems(Type propertyType)
        {
            return new[]
            {
                new SelectListItem { Value = "", Text = "Select a Segment..."},
                new SelectListItem { Value = "c_age_median", Text = "Median Age"},
                new SelectListItem { Value = "c_16_to_19_year_olds_in_school", Text = "School is Cool"},
                new SelectListItem { Value = "c_earth_temperature", Text = "Temperature Trends"},
                new SelectListItem { Value = "c_earth_temperature_amplitude", Text = "Temperature Tendencies"},
                new SelectListItem { Value = "c_high_school_graduate_rate", Text = "Congrats, Grads"},
                new SelectListItem { Value = "c_less_than_hs_education_rate", Text = "Some High School, No Diploma"},
                new SelectListItem { Value = "c_master_s_degree_rate", Text = "Masters of the University"},
                new SelectListItem { Value = "c_electric_consumer_residential", Text = "It's Electric: Residential"},
                new SelectListItem { Value = "c_electric_price_commercial", Text = "Electric Expenses: Commercial"},
                new SelectListItem { Value = "c_electric_consumer_industrial", Text = "It's Electric: Industrial"},
                new SelectListItem { Value = "c_electric_consumers_total", Text = "It's Electric"},
                new SelectListItem { Value = "c_employment_rate", Text = "Nine-to-Five Crew"},
                new SelectListItem { Value = "c_health_insurance_none", Text = "No Health Insurance"},
                new SelectListItem { Value = "c_heating_degree_days", Text = "Warming Up"},
                new SelectListItem { Value = "c_heating_fuel_coal_coke_rate", Text = "Heating Up: Coal Coke"},
                new SelectListItem { Value = "c_heating_fuel_electricity_rate", Text = "Heating Up: Electricity"},
                new SelectListItem { Value = "c_heating_fuel_gas_rate", Text = "Heating Up: Gas"},
                new SelectListItem { Value = "c_house_hold_type_family_rate", Text = "Family Framework"},
                new SelectListItem { Value = "c_incentives_non_residential", Text = "Solar Power Persuasion: Non Residential"},
                new SelectListItem { Value = "c_incentives_residential", Text = "Solar Power Persuasion: Residential"},
                new SelectListItem { Value = "c_mortgage_with_rate", Text = "Mortage Rate Trends"},
                new SelectListItem { Value = "c_net_metering", Text = "Saving for a Rainy Day"},
                new SelectListItem { Value = "c_occupancy_vacant_rate", Text = "Looking for Tenants"},
                new SelectListItem { Value = "c_occupation_admin_rate", Text = "Admin Activity"},
                new SelectListItem { Value = "c_occupation_agriculture_rate", Text = "Down on the Farm"},
                new SelectListItem { Value = "c_occupation_education_rate", Text = "Pedagogical Professionals"},
                new SelectListItem { Value = "c_occupation_finance_rate", Text = "Finance Fanatics"},
                new SelectListItem { Value = "c_occupation_information", Text = "Stay Informed"},
                new SelectListItem { Value = "c_occupation_retail_rate", Text = "Set Sale"},
                new SelectListItem { Value = "c_occupation_transport_rate", Text = "Getting from Point A to Point B"},
                new SelectListItem { Value = "c_occupation_wholesale_rate", Text = "The Incredible Bulk"},
                new SelectListItem { Value = "c_property_tax", Text = "The Tax Man"},
                new SelectListItem { Value = "c_race_asian_rate", Text = "Race: Asian"},
                new SelectListItem { Value = "c_race_other_rate", Text = "Race: Other"},
                new SelectListItem { Value = "c_race_two_more_rate", Text = "Race: Two or More"},
                new SelectListItem { Value = "c_race_white_rate", Text = "Race: White"},
                new SelectListItem { Value = "c_solar_systems_non_residential", Text = "Solar Systems: Non Residential"},
                new SelectListItem { Value = "c_solar_systems_residential", Text = "Solar Systems: Residential"},
                new SelectListItem { Value = "c_tile_count", Text = "Tile Tally"},
                new SelectListItem { Value = "c_total_area", Text = "Solar Resources"},
                new SelectListItem { Value = "c_panel_area_non_residential", Text = "Solar Assets: Non Residential"},
                new SelectListItem { Value = "c_panel_area_residential", Text = "Solar Assets: Residential"},
                new SelectListItem { Value = "c_transport_home_rate", Text = "Working from Home"},
                new SelectListItem { Value = "c_transport_motorcycle_rate", Text = "Motoring to the Office"},
                new SelectListItem { Value = "c_transport_public_rate", Text = "Public Transit"},
                new SelectListItem { Value = "c_travel_time_10_to_19_rate", Text = "Commute Contrast"},
                new SelectListItem { Value = "c_travel_time_20_to_29_rate", Text = "Commuter Comparitive"},
                new SelectListItem { Value = "c_travel_time_60_to_89_rate", Text = "Commuter Chronometer"},
                new SelectListItem { Value = "c_travel_time_less_than_10_rate", Text = "Commuter Convenience"},
                new SelectListItem { Value = "c_voting_2016_dem_percentage", Text = "Dem Voters in 2016"},
                new SelectListItem { Value = "c_voting_2016_gop_percentage", Text = "Republican Vote 2016"},
                new SelectListItem { Value = "c_water_area", Text = "Still Waters Run Deep"},
                new SelectListItem { Value = "c_age_55_to_64_rate", Text = "Baby Boomers"},
                new SelectListItem { Value = "c_age_65_to_74_rate", Text = "Baby Boomers Part 2"},
                new SelectListItem { Value = "c_age_45_to_54_rate", Text = "Gen Xers"},
                new SelectListItem { Value = "c_c_occupation_information", Text = "Occupation 411"},
                new SelectListItem { Value = "c_voting_2012_dem_win", Text = "Dem Winners 2012"},
                new SelectListItem { Value = "c_state_incentive_level", Text = "Original Influencers"},
                new SelectListItem { Value = "c_age_5_to_9_rate", Text = "Kiddos"},
                new SelectListItem { Value = "c_unemployed", Text = "Pounding the Pavement"},
                new SelectListItem { Value = "c_voting_2012_dem_percentage", Text = "Dem Voters in 2012"},
                new SelectListItem { Value = "c_voting_2012_gop_percentage", Text = "Republican Vote 2012"},
                new SelectListItem { Value = "c_wind_speed", Text = "Against the Wind"},
                new SelectListItem { Value = "c_age_10_to_14_rate", Text = "Tweens"},
                new SelectListItem { Value = "c_age_15_to_17_rate", Text = "Teens"},
                new SelectListItem { Value = "c_electricity_avg_retail_rate", Text = "Electricity Expense Rate"},
                new SelectListItem { Value = "c_electric_price_residential", Text = "Private Power Price"},
                new SelectListItem { Value = "c_families_below_poverty_level", Text = "Below the Poverty Line"},
                new SelectListItem { Value = "c_voting_2016_dem_win", Text = "Dem Winners 2016"},
                new SelectListItem { Value = "c_gini_index", Text = "Gini Index"},
                new SelectListItem { Value = "c_family_below_poverty_level", Text = "Family Below Poverty Level"},
                new SelectListItem { Value = "c_occupation_manufacturing_rate", Text = "Positive Production"},
                new SelectListItem { Value = "c_occupation_public_rate", Text = "For the People"},
                new SelectListItem { Value = "c_per_capita_income", Text = "Making Bread"},
                new SelectListItem { Value = "c_population", Text = "Inhabitant Info"},
                new SelectListItem { Value = "c_population_density", Text = "Denizen Denseness"},
                new SelectListItem { Value = "c_race_black_africa_rate", Text = "Race: Black Africa"},
                new SelectListItem { Value = "c_race_indian_alaska_rate", Text = "Race: Indian Alaska"},
                new SelectListItem { Value = "c_race_islander_rate", Text = "Race: Islander"},
                new SelectListItem { Value = "c_relative_humidity", Text = "Oh, the humidity!"},
                new SelectListItem { Value = "c_solar_panel_area_area", Text = "Solar Scheme"},
                new SelectListItem { Value = "c_solar_system_count", Text = "Solar System Count"},
                new SelectListItem { Value = "c_electric_price_industrial", Text = "Electric Expenses: Industrial"},
                new SelectListItem { Value = "c_electric_price_overall", Text = "Electric Expenses"},
                new SelectListItem { Value = "c_electric_price_transportation", Text = "Electric Expenses: Transportation"},
                new SelectListItem { Value = "c_tile_count_non_residential", Text = "Tile Tally: Non Residential"},
                new SelectListItem { Value = "c_tile_count_residential", Text = "Tile Tally: Residential"},
                new SelectListItem { Value = "c_frost_days", Text = "Frosty Days"},
                new SelectListItem { Value = "c_heating_fuel_solar_rate", Text = "Heating Up: Solar"},
                new SelectListItem { Value = "c_heating_design_temperature", Text = "Heat Expectations"},
                new SelectListItem { Value = "c_heating_fuel_housing_units", Text = "Heating Up: Housing Units"},
                new SelectListItem { Value = "c_transport_bicycle_rate", Text = "Biking to Work"},
                new SelectListItem { Value = "c_transport_car_pool_rate", Text = "Car Pooling"},
                new SelectListItem { Value = "c_heating_fuel_none_rate", Text = "Heating Up: None"},
                new SelectListItem { Value = "c_heating_fuel_kerosene_rate", Text = "Heating Up: Kerosene"},
                new SelectListItem { Value = "c_heating_fuel_other_rate", Text = "Heating Up: Other"},
                new SelectListItem { Value = "c_housing_unit_median_gross_rent", Text = "For Rent"},
                new SelectListItem { Value = "c_housing_unit_median_value", Text = "Market Price"},
                new SelectListItem { Value = "c_transport_walk_rate", Text = "Walking to Work"},
                new SelectListItem { Value = "c_travel_time_average", Text = "Commute Comparison"},
                new SelectListItem { Value = "c_incentives_residential_state", Text = "Solar Power Persuasion: Residential State"},
                new SelectListItem { Value = "c_insurance_public_rate", Text = "An Ounce of Prevention"},
                new SelectListItem { Value = "c_median_household_income", Text = "Average Family Income"},
                new SelectListItem { Value = "c_number_of_years_of_education", Text = "School Days"},
                new SelectListItem { Value = "c_occupancy_owner_rate", Text = "No Vacancy"},
                new SelectListItem { Value = "c_age_35_to_44_rate", Text = "Millennials & Gen-X"},
                new SelectListItem { Value = "c_age_75_to_84_rate", Text = "Silent Boomers"},
                new SelectListItem { Value = "c_cooling_design_temperature", Text = "Cool It"},
                new SelectListItem { Value = "c_daily_solar_radiation", Text = "Ray Days"},
                new SelectListItem { Value = "c_diversity", Text = "Melting Pot"},
                new SelectListItem { Value = "c_travel_time_30_to_39_rate", Text = "Commuters' Commute"},
                new SelectListItem { Value = "c_travel_time_40_to_59_rate", Text = "Commuter Clock Time"},
                new SelectListItem { Value = "c_bachelor_s_degree_rate", Text = "Baccalaureates"},
                new SelectListItem { Value = "c_some_college_education_rate", Text = "Some College, No Degree"},
                new SelectListItem { Value = "c_doctoral_degree_rate", Text = "What's up, Doc?"},
                new SelectListItem { Value = "c_occupation_arts_rate", Text = "Fine Art"},
                new SelectListItem { Value = "c_occupation_construction_rate", Text = "The Builder's Guild"},
                new SelectListItem { Value = "c_education_population", Text = "Gen Ed"},
                new SelectListItem { Value = "c_professional_degree_rate", Text = "Career Focused"},
                new SelectListItem { Value = "c_electric_consumer_commercial", Text = "It's Electric: Commercial"},
                new SelectListItem { Value = "c_age_18_to_24_rate", Text = "Generation Z"},
                new SelectListItem { Value = "c_age_25_to_34_rate", Text = "Millennials"},
                new SelectListItem { Value = "c_age_more_than_85_rate", Text = "Over 85s"},
                new SelectListItem { Value = "c_air_temperature", Text = "Running Air Temperature"},
                new SelectListItem { Value = "c_atmospheric_pressure", Text = "Under (Atmospheric) Pressure"},
                new SelectListItem { Value = "c_average_household_income", Text = "Median Moolah Made"},
                new SelectListItem { Value = "c_average_household_size", Text = "The Average Abode"},
                new SelectListItem { Value = "c_car_alone_rate", Text = "Car Alone Rate"},
                new SelectListItem { Value = "c_cooling_degree_days", Text = "Cooling Degree Days"}
            };
        }
    }
}